name: 🚀 Main Branch - Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Build Project
        run: dotnet restore; dotnet publish -o site;

      - name: create zip file
        run: cd site; zip ../site.zip *;

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          application_name: Api_ENDE_Crypt-KYH
          environment_name: ApiENDECrypt-KYH-env
          version_label: ${{ github.run_id }}
          deployment_package: site.zip